apiVersion: v1
kind: Secret
metadata:
  name: image-service-secret
type: Opaque
stringData:
  # Fill these with your AWS credentials or leave empty to use IAM role / IRSA
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
