{
	"name": "@chirp/client-user",
	"version": "1.0.0",
	"private": true,
	"type": "module",
	"scripts": {
		"dev": "vite dev --port 3000",
		"build": "vite build",
		"start": "node .output/server/index.mjs",
		"preview": "vite preview",
		"lint": "biome check .",
		"lint:fix": "biome check --write .",
		"typecheck": "tsc --noEmit",
		"test": "pnpm run test:unit",
		"test:unit": "vitest run",
		"test:e2e": "playwright test"
	},
	"dependencies": {
		"@chirp/grpc-client": "workspace:*",
		"@chirp/proto": "workspace:*",
		"@chirp/ui": "workspace:*",
		"@grpc/grpc-js": "^1.12.6",
		"@stylexjs/stylex": "^0.17.5",
		"@tanstack/react-devtools": "^0.7.0",
		"@tanstack/react-query": "^5.90.16",
		"@tanstack/react-router": "^1.132.0",
		"@tanstack/react-router-devtools": "^1.132.0",
		"@tanstack/react-router-ssr-query": "^1.131.7",
		"@tanstack/react-start": "^1.132.0",
		"@tanstack/router-plugin": "^1.132.0",
		"clsx": "^2.1.1",
		"jsonwebtoken": "^9.0.2",
		"lucide-react": "^0.561.0",
		"nitro": "npm:nitro-nightly@latest",
		"react": "^19.2.0",
		"react-dom": "^19.2.0",
		"vite-tsconfig-paths": "^6.0.2"
	},
	"devDependencies": {
		"@biomejs/biome": "^2.3.11",
		"@playwright/test": "^1.57.0",
		"@stylexjs/unplugin": "^0.17.5",
		"@tanstack/devtools-vite": "^0.3.11",
		"@testing-library/dom": "^10.4.0",
		"@testing-library/jest-dom": "^6.9.1",
		"@testing-library/react": "^16.2.0",
		"@testing-library/user-event": "^14.6.1",
		"@types/jsonwebtoken": "^9.0.9",
		"@types/node": "^22.10.2",
		"@types/react": "^19.2.0",
		"@types/react-dom": "^19.2.0",
		"@vitejs/plugin-react": "^5.0.4",
		"jsdom": "^27.0.0",
		"tsx": "^4.21.0",
		"typescript": "^5.7.2",
		"vite": "^7.1.7",
		"vitest": "^3.0.5"
	}
}
