/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as BookmarksRouteImport } from "./routes/bookmarks";
import { Route as ExploreRouteImport } from "./routes/explore";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as PostsPostIdRouteImport } from "./routes/posts/$postId";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as UsersUsernameRouteImport } from "./routes/users/$username";

const SearchRoute = SearchRouteImport.update({
	id: "/search",
	path: "/search",
	getParentRoute: () => rootRouteImport,
} as any);
const NotificationsRoute = NotificationsRouteImport.update({
	id: "/notifications",
	path: "/notifications",
	getParentRoute: () => rootRouteImport,
} as any);
const ExploreRoute = ExploreRouteImport.update({
	id: "/explore",
	path: "/explore",
	getParentRoute: () => rootRouteImport,
} as any);
const BookmarksRoute = BookmarksRouteImport.update({
	id: "/bookmarks",
	path: "/bookmarks",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const UsersUsernameRoute = UsersUsernameRouteImport.update({
	id: "/users/$username",
	path: "/users/$username",
	getParentRoute: () => rootRouteImport,
} as any);
const PostsPostIdRoute = PostsPostIdRouteImport.update({
	id: "/posts/$postId",
	path: "/posts/$postId",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
	id: "/auth/register",
	path: "/auth/register",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
	id: "/auth/login",
	path: "/auth/login",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/bookmarks": typeof BookmarksRoute;
	"/explore": typeof ExploreRoute;
	"/notifications": typeof NotificationsRoute;
	"/search": typeof SearchRoute;
	"/auth/login": typeof AuthLoginRoute;
	"/auth/register": typeof AuthRegisterRoute;
	"/posts/$postId": typeof PostsPostIdRoute;
	"/users/$username": typeof UsersUsernameRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/bookmarks": typeof BookmarksRoute;
	"/explore": typeof ExploreRoute;
	"/notifications": typeof NotificationsRoute;
	"/search": typeof SearchRoute;
	"/auth/login": typeof AuthLoginRoute;
	"/auth/register": typeof AuthRegisterRoute;
	"/posts/$postId": typeof PostsPostIdRoute;
	"/users/$username": typeof UsersUsernameRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/bookmarks": typeof BookmarksRoute;
	"/explore": typeof ExploreRoute;
	"/notifications": typeof NotificationsRoute;
	"/search": typeof SearchRoute;
	"/auth/login": typeof AuthLoginRoute;
	"/auth/register": typeof AuthRegisterRoute;
	"/posts/$postId": typeof PostsPostIdRoute;
	"/users/$username": typeof UsersUsernameRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/bookmarks"
		| "/explore"
		| "/notifications"
		| "/search"
		| "/auth/login"
		| "/auth/register"
		| "/posts/$postId"
		| "/users/$username";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/bookmarks"
		| "/explore"
		| "/notifications"
		| "/search"
		| "/auth/login"
		| "/auth/register"
		| "/posts/$postId"
		| "/users/$username";
	id:
		| "__root__"
		| "/"
		| "/bookmarks"
		| "/explore"
		| "/notifications"
		| "/search"
		| "/auth/login"
		| "/auth/register"
		| "/posts/$postId"
		| "/users/$username";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	BookmarksRoute: typeof BookmarksRoute;
	ExploreRoute: typeof ExploreRoute;
	NotificationsRoute: typeof NotificationsRoute;
	SearchRoute: typeof SearchRoute;
	AuthLoginRoute: typeof AuthLoginRoute;
	AuthRegisterRoute: typeof AuthRegisterRoute;
	PostsPostIdRoute: typeof PostsPostIdRoute;
	UsersUsernameRoute: typeof UsersUsernameRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/search": {
			id: "/search";
			path: "/search";
			fullPath: "/search";
			preLoaderRoute: typeof SearchRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/notifications": {
			id: "/notifications";
			path: "/notifications";
			fullPath: "/notifications";
			preLoaderRoute: typeof NotificationsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/explore": {
			id: "/explore";
			path: "/explore";
			fullPath: "/explore";
			preLoaderRoute: typeof ExploreRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/bookmarks": {
			id: "/bookmarks";
			path: "/bookmarks";
			fullPath: "/bookmarks";
			preLoaderRoute: typeof BookmarksRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/users/$username": {
			id: "/users/$username";
			path: "/users/$username";
			fullPath: "/users/$username";
			preLoaderRoute: typeof UsersUsernameRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/posts/$postId": {
			id: "/posts/$postId";
			path: "/posts/$postId";
			fullPath: "/posts/$postId";
			preLoaderRoute: typeof PostsPostIdRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/register": {
			id: "/auth/register";
			path: "/auth/register";
			fullPath: "/auth/register";
			preLoaderRoute: typeof AuthRegisterRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/auth/login": {
			id: "/auth/login";
			path: "/auth/login";
			fullPath: "/auth/login";
			preLoaderRoute: typeof AuthLoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	BookmarksRoute: BookmarksRoute,
	ExploreRoute: ExploreRoute,
	NotificationsRoute: NotificationsRoute,
	SearchRoute: SearchRoute,
	AuthLoginRoute: AuthLoginRoute,
	AuthRegisterRoute: AuthRegisterRoute,
	PostsPostIdRoute: PostsPostIdRoute,
	UsersUsernameRoute: UsersUsernameRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
